# Generated by Django 5.2.13 on 2026-04-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='devlog/%Y/%m/%d/'),
        ),
    ]
